### ISSUE TITLE
Client is disconnected on join when Spelunkery is present

### ISSUE THREAD

**Issue by Abbie5** [Abbie5/emi-ores#1]

**Comment by Abbie5** [comment]
Log for future me 
[latest.log](https://github.com/Abbie5/emi-ores/files/14409232/latest.log)

**Comment by Abbie5** [comment]
I believe the game is unable to serialise the block predicate filter for some reason, see https://github.com/AstralOrdana/Spelunkery/blob/d06910226eab5086462138baf81f38abeb8893bd/common/src/main/resources/data/spelunkery/worldgen/placed_feature/ore_aquifer.json#L42 and https://github.com/Stardust-Labs-MC/Terralith/blob/e8293d1eebc0ad7fa92c43b82d7d40815d34ca90/data/terralith/worldgen/placed_feature/cave/generic/ds_reducer.json#L28

**Comment by Abbie5** [comment]
Fixed in 0b00f57

**Comment by unilock** [comment]
This also (still) occurs with [Crossroads](https://modrinth.com/mod/crossroads) installed (and EMI Ores running via [Sinytra Connector](https://modrinth.com/mod/connector)).

Maybe EMI Ores could print the ResourceLocation of the feature it's failing to decode, and have a config to disable problematic features (by ResourceLocation)?

**Comment by Abbie5** [comment]
Thanks, I'll have a look.

**Comment by Abbie5** [comment]
To note, I have tested the above commit with Crossroads, and there is no client disconnect.

**Comment by Abbie5** [comment]
Sorry it took so long @unilock, the fix is now published in version 0.3.

**Comment by unilock** [comment]
Awesome, thanks!
