### ISSUE TITLE
Request for 1.21 branch

### ISSUE THREAD

**Issue by ghost** [Abbie5/emi-ores#14]
Hey, been porting EMI Ores today since they doesn't seem to be any great ore-viewer for NeoForge 1.21 yet...

Would I be able to get a 1.21 branch created so I can PR my work, is frankly quite the ummm functional port, if I were you I'd give it a once over or maybe even a twice over to make sure your happy with it.

Oh and here's my branch, feel free to just push it directly if you want or what ever else I don't really care too much ^_^

https://github.com/quinn-semele/emi-ores/tree/1.21

and an easy diff url

https://github.com/quinn-semele/emi-ores/compare/00c7bf0..HEAD

**Comment by Abbie5** [comment]
Thanks so much for your work on the port! I have created the 1.21 branch now so feel free to open a PR.
