### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by spinodal23** [Abbie5/emi-ores#18]
I hope this mod updated to 1.21.1.
Is there any ETA, or no ETA?
Or it will not be updated?

**Comment by Abbie5** [comment]
1.21.1 support is planned. no eta however.

**Comment by EngiN33R** [comment]
@Abbie5 Given that https://github.com/Abbie5/emi-ores/pull/15 exists, would it be possible for you to review it and leave a comment regarding any other required changes? I'd be happy to contribute to that PR myself to bring this mod up to date quickly.

**Comment by Abbie5** [comment]
fixed in #15
