### ISSUE TITLE
Feature request: Change visualization of biome restriction to a plain list

### ISSUE THREAD

**Issue by Sl-L** [Abbie5/emi-ores#20]
Currently the biome restriction is shown as a picture and cycles through. When using mods that add biomes (e.g.: Biome's O' Plenty) it becomes tedious to wait for the cycling, it would be nice to be able to see all the biomes at once in text form.

**Comment by Abbie5** [comment]
Hi, can you please test again with version 1.0? You should be able to click on the biome to get to a list of all biomes that the ore can generate in.

**Comment by Sl-L** [comment]
Tested just now. Can confirm that it works, at least in 1.20.1, in both fabric and forge
