### ISSUE TITLE
[1.21.1][Neoforge] Occultism Ore With wrong Nether Y levels

### ISSUE THREAD

**Issue by ffuentesm** [Abbie5/emi-ores#25]
emi_ores-1.0+1.21.1+neoforge

I assume the Nether just goes from y-0 to y- 124 right? 
So why is this graph showing a negative Y level range? 

![image](https://github.com/user-attachments/assets/484a5533-2b96-4099-b7a5-458f6a29043c)
![image](https://github.com/user-attachments/assets/e8346905-de3b-4ee6-a20e-97bc1fa939c2)
![image](https://github.com/user-attachments/assets/e63aca23-e5d5-4508-9a0d-fb7acebbbb40)

**Comment by Abbie5** [comment]
This is correct as per Occultism's data. https://github.com/klikli-dev/occultism/blob/9ef9f9611fbd06328fc375bcc940f89f97082ffa/src/generated/resources/data/occultism/worldgen/placed_feature/ore_iesnium.json#L13

When generating ores, if a y-value is picked that is outside of the world limits, it is skipped. So the net effect is that this ore generates more frequently the further down you go.
