### ISSUE TITLE
Unified Ores not showing on the Ore Generation Tab

### ISSUE THREAD

**Issue by ffuentesm** [Abbie5/emi-ores#31]
I don't know why, but some ores don't show up on the Ore Generation tab when certain mods are installed. 
I think it might be the Almost Unified mod causing this problem. When I try to check the Ore Generation of an ore that was Unified, it shows nothing. When I click on an ore that was not Unified, it shows its generation.

Platinum Ore not unified:
![image](https://github.com/user-attachments/assets/2c62a9d5-0491-4c8a-ac6f-e4004abf70c8)
![image](https://github.com/user-attachments/assets/45b9fe70-83e0-4b14-945a-18d0bf6969c3)

Unified Platinum Ore:
![image](https://github.com/user-attachments/assets/23699fc1-7a68-4186-ad66-4e2f07ebad4d)

This might be a AU problem, but I wanted to check on this end too.

**Comment by Abbie5** [comment]
Hm, I think I need some more information in order to understand this

What is the difference between something that is "unified" vs "not unified"?
Do "unified" ores generate in the world?

**Comment by ffuentesm** [comment]
Yes, both ores till Generate in the world. The difference is that the duplicated ores will be removed from the EMI list. 
The item drops will be converted into the Unified variant. 
So, an ATO and Oritech Platinum Ore will spawn in their respective levels, but if I set ATO as the primary Mod; when I break either of those ores, it will drop the ATO Raw Platinum Ore variant. 

The same goes for recipes, any form of processing or recipe will output the primary ore, in case there are duplicated outputs. 
So things like Ingots will have a single variant instead of different mod variants. 

I also opened an Issue on the AU discord server: https://discord.com/channels/917251858974789693/1316461699154444298
There they said: AlmostUnified just uses the NeoForge entry point for biome modifiers to remove features. If emi-ores analyze the data before NeoForge stuff, then nothing we can do.

**Comment by Abbie5** [comment]
is `emi_strict_hiding` enabled in Almost Unified's `tags.json` config file? As far as I understand it, this setting makes it so that (among other things) recipes that output the items that have been hidden by the unification will also be hidden. This would include EMI Ores' ore generation recipes. In my opinion, this is intended behaviour.

**Comment by ffuentesm** [comment]
hum, strange. 
Yes, I have that section enabled. 
I find it weird, since even when the ores are unified. ATO has a Nether and End Variants of those ores, so only the Stone and Deepslate are unified. So having everything hidden was not something I expected. Just that those variants would no longer show up in the Tabs. 

Seems that disabling that option made it work as I presumed.
