### ISSUE TITLE
[Feature Request] NeoForge Support 1.20.1+

### ISSUE THREAD

**Issue by D4RKAR117** [Abbie5/emi-ores#7]
This add-on has a lot of potential, filling the only gap that EMI has when using  it on large modpacks.
It would be great that the releases would be targeted for neoforge v1.20.1 alongside fabric like EMI core does

**Comment by Abbie5** [comment]
NeoForge on 1.20.1 supports Forge mods, so that is covered by #3. For 1.20.4 and beyond I will also switch from supporting Forge to NeoForge.
